apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::933869125920:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-YlFomCDA8s7Z
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::933869125920:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-31T03:13:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1356"
  uid: 28c00d53-a922-4c52-8d69-6246d908b416
